version: "2"

services:
  app_cyber:
      build: ./cybermonday
      ports:
        - "5000:5000"
      networks:
        - jaeger-elasticsearch-compose_elastic-jaeger
      volumes:
        - './cybermonday:/cybermonday'
      command: ["python", "/cybermonday/cyber.py"]

  db_auth:
      image: postgres:9.6
      restart: always
      environment:
            POSTGRES_PASSWORD: s3cureauth
      ports:
        - "5432:5432"
      networks:
        - jaeger-elasticsearch-compose_elastic-jaeger
      volumes:
        - './auth/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql'
        - './auth/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql'

  app_auth:
      depends_on:
        - app_cyber
        - db_auth
      build: ./auth
      ports:
        - "5001:5001"
      networks:
        - jaeger-elasticsearch-compose_elastic-jaeger
      volumes:
        - './auth:/auth'
      command: ["python", "/auth/auth.py"]

networks:
  jaeger-elasticsearch-compose_elastic-jaeger:
      external: true
